[workspace]
members = [
    "crates/app",
    "crates/display",
    "crates/editor",
    "crates/language",
    "crates/multibuffer",
    "crates/project",
    "crates/rope",
    "crates/text",
    "crates/ui",
    "crates/workspace"
]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"

[workspace.dependencies]
display = { path = "crates/display" }
editor = { path = "crates/editor" }
language = { path = "crates/language" }
multibuffer = { path = "crates/multibuffer" }
project = { path = "crates/project" }
rope = { path = "crates/rope" }
text = { path = "crates/text" }
ui = { path = "crates/ui" }
workspace = { path = "crates/workspace" }

gpui = { version = "0.2.2", features = ["test-support"] }
